services:
  springboot-service:
    build:
      context: .                    # Spring Boot Dockerfile 경로
      dockerfile: Dockerfile        # Spring Boot Dockerfile 파일명
    ports:
      - "8081:8081"                 # Spring Boot 서버 포트 매핑
    depends_on:
      - python-service              # Python 서비스가 먼저 실행됨
      - db-service

    environment:
      - PYTHON_SERVICE_URL=http://python-service:5000 # Python 서비스의 URL
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-service:3307/sketch_db # DB URL
      - SPRING_DATASOURCE_USERNAME=root # DB 사용자명
      - SPRING_DATASOURCE_PASSWORD=Dd905925@ # DB 비밀번호

  python-service:
    build:
      context: ./python-flask-app   # Python Dockerfile 경로
      dockerfile: Dockerfile-python # Python Flask Dockerfile 파일명
    ports:
      - "5002:5000"                 # 호스트의 5001 포트를 Flask 컨테이너의 5000 포트에 매핑
    environment:
      - OPENAI_API_KEY=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

  db-service:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Dd905925@
      - MYSQL_DATABASE=sketch_db
    ports:
      - "3307:3306"                 # 호스트의 3307 포트를 컨테이너의 3306 포트에 매핑
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: