spring.application.name=sketch
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/sketch_db
spring.datasource.username=root
spring.datasource.password=Dd905925@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret = 8f844107ba85cba835657a66b04ac9afe20cbdbf8a6273749acaade1fe4d8b7c
PYTHON_SERVICE_URL=http://localhost:5000