spring.application.name=sketch
server.port=8088

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:~/local
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret = 8f844107ba85cba835657a66b04ac9afe20cbdbf8a6273749acaade1fe4d8b7c
