FROM ubuntu:latest
LABEL authors="cuhun"

ENTRYPOINT ["top", "-b"]

# Python 3.9 이미지 사용
FROM python:3.9-slim

# 작업 디렉터리 설정
WORKDIR /app

# 코드 복사
COPY app.py /app/

# 필요한 패키지 설치
RUN pip install flask langchain-openai langchain-core

# Flask 서버 포트 노출
EXPOSE 5000

# Flask 서버 실행
CMD ["python", "app.py"]

